import { LOCALE_NAMES, SUPPORTED_LOCALES, SYSTEM_LOCALE, setAppLocale } from '$lib/i18n';
import { onHarperChanged, onLogLevelChange, onThemeChange, reloadSpellcheck } from './settingsHandlers';

export type SettingDef = {
  key: string;
  label: string;
  type: string;
  category: string;
  defaultValue: unknown;
  options?: string[];
  optionLabels?: string[];
  min?: number;
  max?: number;
  step?: number;
  tooltip?: string;
  visibleWhen?: { key: string; value: unknown };
  groupWith?: string;
  onChange?: (newValue: unknown, oldValue: unknown) => void;
};

export function getSettingDefinitions(availableThemes: string[], isWindows: boolean): SettingDef[] {
  return [
    {
      key: 'logLevel',
      label: 'settings.logLevel',
      type: 'select',
      category: 'settings.category.system',
      defaultValue: 'info',
      options: ['trace', 'debug', 'info', 'warn', 'error'],
      tooltip: 'settings.logLevelTooltip',
      onChange: onLogLevelChange,
    },

    {
      key: 'newFileTemplatePath',
      label: 'settings.newFileTemplate',
      type: 'file',
      category: 'settings.category.editor',
      defaultValue: '',
      tooltip: 'settings.newFileTemplateTooltip',
    },

    {
      key: 'activeTheme',
      label: 'settings.theme',
      type: 'select',
      category: 'settings.category.interface',
      defaultValue: 'System',
      options: availableThemes,
      tooltip: 'settings.themeTooltip',
      onChange: onThemeChange,
    },

    {
      key: 'customAccentColor',
      label: 'settings.customAccentColor',
      type: 'color',
      category: 'settings.category.interface',
      defaultValue: '',
      tooltip: 'settings.customAccentColorTooltip',
    },

    {
      key: 'viewMode',
      label: 'settings.viewMode',
      type: 'select',
      category: 'settings.category.editor',
      defaultValue: 'rendered',
      options: ['raw', 'rendered'],
      optionLabels: ['settings.viewModeRaw', 'settings.viewModeRendered'],
      tooltip: 'settings.viewModeTooltip',
    },
    {
      key: 'editorFontFamily',
      label: 'settings.fontFamily',
      type: 'text',
      category: 'settings.category.editor',
      defaultValue: 'monospace',
      tooltip: 'settings.fontFamilyTooltip',
    },
    {
      key: 'editorFontSize',
      label: 'settings.fontSizePx',
      type: 'number',
      category: 'settings.category.editor',
      defaultValue: 14,
      min: 8,
      max: 32,
      tooltip: 'settings.fontSizeTooltip',
    },
    {
      key: 'wrapGuideColumn',
      label: 'settings.wrapColumn',
      type: 'number',
      category: 'settings.category.editor',
      defaultValue: 0,
      min: -1,
      max: 500,
      tooltip: 'settings.wrapColumnTooltip',
    },
    {
      key: 'showWhitespace',
      label: 'settings.whitespaceDisplayed',
      type: 'boolean',
      category: 'settings.category.editor',
      defaultValue: false,
      tooltip: 'settings.whitespaceTooltip',
    },
    {
      key: 'autocompleteDelay',
      label: 'settings.autocompleteDelayMs',
      type: 'number',
      category: 'settings.category.editor',
      defaultValue: 850,
      min: -1,
      max: 2000,
      tooltip: 'settings.autocompleteDelayTooltip',
    },
    {
      key: 'showMinimap',
      label: 'settings.minimap',
      type: 'boolean',
      category: 'settings.category.editor',
      defaultValue: false,
      tooltip: 'settings.minimapTooltip',
    },
    {
      key: 'writerWrapLength',
      label: 'settings.writerWrapLength',
      type: 'number',
      category: 'settings.category.editor',
      defaultValue: 100,
      min: 40,
      max: 200,
      tooltip: 'settings.writerWrapLengthTooltip',
    },
    {
      key: 'defaultIndent',
      label: 'settings.defaultIndent',
      type: 'number',
      category: 'settings.category.editor',
      defaultValue: 2,
      min: 2,
      max: 8,
      tooltip: 'settings.defaultIndentTooltip',
    },
    {
      key: 'recentChangesCount',
      label: 'settings.recentChangesCount',
      type: 'number',
      category: 'settings.category.editor',
      defaultValue: 16,
      // -1 disables recent-changes highlighting, matching the check in
      // recentChangesExtension (count > 0).
      min: -1,
      max: 99,
      tooltip: 'settings.recentChangesCountTooltip',
    },
    {
      key: 'recentChangesTimespan',
      label: 'settings.recentChangesTimespan',
      type: 'number',
      category: 'settings.category.editor',
      defaultValue: 600,
      min: 0,
      max: 9999,
      groupWith: 'recentChangesCount',
      tooltip: 'settings.recentChangesTimespanTooltip',
    },
    {
      key: 'autoSaveInterval',
      label: 'settings.autoSaveInterval',
      type: 'number',
      category: 'settings.category.editor',
      defaultValue: -1,
      min: -1,
      max: 3600,
      tooltip: 'settings.autoSaveIntervalTooltip',
    },
    {
      key: 'lineEndingPreference',
      label: 'settings.lineEnding',
      type: 'select',
      category: 'settings.category.editor',
      defaultValue: 'system',
      options: ['system', 'LF', 'CRLF'],
      optionLabels: ['settings.lineEndingSystem', 'settings.lineEndingLF', 'settings.lineEndingCRLF'],
      tooltip: 'settings.lineEndingTooltip',
    },
    {
      key: 'formatOnSave',
      label: 'settings.formatOnSave',
      type: 'boolean',
      category: 'settings.category.formatting',
      defaultValue: false,
      tooltip: 'settings.formatOnSaveTooltip',
    },
    {
      key: 'tabWidthMin',
      label: 'settings.tabWidthMin',
      type: 'number',
      category: 'settings.category.interface',
      defaultValue: 120,
      min: 80,
      max: 300,
      tooltip: 'settings.tabWidthMinTooltip',
    },
    {
      key: 'tabWidthMax',
      label: 'settings.tabWidthMax',
      type: 'number',
      category: 'settings.category.interface',
      defaultValue: 180,
      min: 100,
      max: 400,
      tooltip: 'settings.tabWidthMaxTooltip',
    },
    {
      key: 'collapsePinnedTabs',
      label: 'settings.pinnedTabsCollapse',
      type: 'boolean',
      category: 'settings.category.interface',
      defaultValue: false,
      tooltip: 'settings.pinnedTabsCollapseTooltip',
    },
    {
      key: 'tabCycling',
      label: 'settings.tabCycling',
      type: 'select',
      category: 'settings.category.interface',
      defaultValue: 'mru',
      options: ['sequential', 'mru'],
      optionLabels: ['settings.tabCyclingSequential', 'settings.tabCyclingMru'],
      tooltip: 'settings.tabCyclingTooltip',
    },
    {
      key: 'tabNameFromContent',
      label: 'settings.tabsNamedFromContent',
      type: 'boolean',
      category: 'settings.category.interface',
      defaultValue: false,
      tooltip: 'settings.tabsNamedFromContentTooltip',
    },
    {
      key: 'enableClosedTabHistory',
      label: 'settings.closedTabHistory',
      type: 'boolean',
      category: 'settings.category.interface',
      defaultValue: true,
      tooltip: 'settings.closedTabHistoryTooltip',
    },
    {
      key: 'fileHistoryLimit',
      label: 'settings.fileHistoryLimit',
      type: 'number',
      category: 'settings.category.interface',
      defaultValue: 999,
      min: 0,
      max: 999,
      step: 1,
      tooltip: 'settings.fileHistoryLimitTooltip',
    },
    {
      key: 'newTabPosition',
      label: 'settings.tabsCreatedAt',
      type: 'select',
      category: 'settings.category.interface',
      defaultValue: 'end',
      options: ['beginning', 'right', 'end'],
      optionLabels: ['settings.tabsCreatedAtBeginning', 'settings.tabsCreatedAtRight', 'settings.tabsCreatedAtEnd'],
      tooltip: 'settings.tabsCreatedAtTooltip',
    },
    {
      key: 'startupBehavior',
      label: 'settings.tabStartup',
      type: 'select',
      category: 'settings.category.interface',
      defaultValue: 'last-focused',
      options: ['first', 'last-focused', 'new'],
      optionLabels: ['settings.tabStartupFirst', 'settings.tabStartupLastFocused', 'settings.tabStartupNew'],
      tooltip: 'settings.tabStartupTooltip',
    },
    {
      key: 'statusBarTransparency',
      label: 'settings.statusBarTransparency',
      type: 'range',
      category: 'settings.category.interface',
      defaultValue: 0,
      min: 0,
      max: 100,
      step: 5,
      tooltip: 'settings.statusBarTransparencyTooltip',
    },
    {
      key: 'tooltipDelay',
      label: 'settings.tooltipDelayMs',
      type: 'number',
      category: 'settings.category.interface',
      defaultValue: 1250,
      min: 0,
      max: 5000,
      tooltip: 'settings.tooltipDelayTooltip',
    },
    {
      key: 'findPanelTransparent',
      label: 'settings.findPanelHides',
      type: 'boolean',
      category: 'settings.category.interface',
      defaultValue: false,
      tooltip: 'settings.findPanelHidesTooltip',
    },
    {
      key: 'findPanelCloseOnBlur',
      label: 'settings.findPanelCloseOnBlur',
      type: 'boolean',
      category: 'settings.category.interface',
      defaultValue: false,
      tooltip: 'settings.findPanelCloseOnBlurTooltip',
    },
    {
      key: 'confirmationSuppressed',
      label: 'settings.confirmationsSuppressed',
      type: 'boolean',
      category: 'settings.category.interface',
      defaultValue: false,
      tooltip: 'settings.confirmationsSuppressedTooltip',
    },
    {
      key: 'locale',
      label: 'settings.language',
      type: 'select',
      category: 'settings.category.interface',
      defaultValue: 'system',
      options: [SYSTEM_LOCALE, ...SUPPORTED_LOCALES],
      optionLabels: ['settings.languageSystem', ...SUPPORTED_LOCALES.map((l) => LOCALE_NAMES[l])],
      tooltip: 'settings.languageTooltip',
      onChange: (value) => setAppLocale(String(value)),
    },

    {
      key: 'previewFontFamily',
      label: 'settings.previewFontFamily',
      type: 'text',
      category: 'settings.category.preview',
      defaultValue: 'sans-serif',
      tooltip: 'settings.previewFontFamilyTooltip',
    },
    {
      key: 'previewFontSize',
      label: 'settings.previewFontSize',
      type: 'number',
      category: 'settings.category.preview',
      defaultValue: 16,
      min: 10,
      max: 32,
      tooltip: 'settings.previewFontSizeTooltip',
    },
    {
      key: 'markdownFlavor',
      label: 'settings.markdownFlavor',
      type: 'select',
      category: 'settings.category.preview',
      defaultValue: 'gfm',
      options: ['gfm', 'commonmark'],
      optionLabels: ['settings.markdownFlavorGfm', 'settings.markdownFlavorCommonmark'],
      tooltip: 'settings.markdownFlavorTooltip',
    },

    {
      key: 'languageDictionaries',
      label: 'settings.languageDictionaries',
      type: 'dictionary-multi-select',
      category: 'settings.category.spellcheck',
      defaultValue: ['en-US'],
      tooltip: 'settings.languageDictionariesTooltip',
      onChange: reloadSpellcheck,
    },
    {
      key: 'technicalDictionaries',
      label: 'settings.technicalDictionaries',
      type: 'boolean',
      category: 'settings.category.spellcheck',
      defaultValue: false,
      tooltip: 'settings.technicalDictionariesTooltip',
      onChange: reloadSpellcheck,
    },
    {
      key: 'scienceDictionaries',
      label: 'settings.scienceDictionaries',
      type: 'boolean',
      category: 'settings.category.spellcheck',
      defaultValue: false,
      tooltip: 'settings.scienceDictionariesTooltip',
      onChange: reloadSpellcheck,
    },

    {
      key: 'harperEnabled',
      label: 'settings.harperEnabled',
      type: 'boolean',
      category: 'settings.category.grammar',
      defaultValue: true,
      tooltip: 'settings.harperEnabledTooltip',
      onChange: onHarperChanged,
    },

    ...(isWindows
      ? [
          {
            key: 'windowsContextMenu',
            label: 'settings.contextMenuEnabled',
            type: 'custom-context-menu',
            category: 'settings.category.system',
            defaultValue: false,
            tooltip: 'settings.contextMenuEnabledTooltip',
          },
        ]
      : []),
  ];
}
