import { onLogLevelChange, onThemeChange, reloadSpellcheck } from './settingsHandlers';

export type SettingDef = {
  key: string;
  label: string;
  type: string;
  category: string;
  defaultValue: unknown;
  options?: string[];
  optionLabels?: string[];
  min?: number;
  max?: number;
  step?: number;
  tooltip?: string;
  visibleWhen?: { key: string; value: unknown };
  groupWith?: string;
  onChange?: (newValue: unknown, oldValue: unknown) => void;
};

export function getSettingDefinitions(availableThemes: string[], isWindows: boolean): SettingDef[] {
  return [
    {
      key: 'logLevel',
      label: 'Log Level (Restart Required)',
      type: 'select',
      category: 'Advanced',
      defaultValue: 'info',
      options: ['trace', 'debug', 'info', 'warn', 'error'],
      tooltip: 'Controls the verbosity of application logs. Requires restart to take effect.',
      onChange: onLogLevelChange,
    },

    {
      key: 'newFileTemplatePath',
      label: 'New File Template',
      type: 'file',
      category: 'File',
      defaultValue: '',
      tooltip: 'Use a Markdown file as the template content for new files. Leave empty to create blank files.',
    },

    {
      key: 'activeTheme',
      label: 'Theme',
      type: 'select',
      category: 'Appearance',
      defaultValue: 'System',
      options: availableThemes,
      tooltip: 'Select the application theme. Changes apply immediately.',
      onChange: onThemeChange,
    },

    {
      key: 'viewMode',
      label: 'Editor View Mode',
      type: 'select',
      category: 'Editor',
      defaultValue: 'rendered',
      options: ['raw', 'rendered'],
      optionLabels: ['Raw Mode', 'Rendered Mode'],
      tooltip: 'Raw: edit Markdown source directly. Rendered: see formatted output while editing.',
    },
    {
      key: 'editorFontFamily',
      label: 'Font Family',
      type: 'text',
      category: 'Editor',
      defaultValue: "'Source Code Pro', 'Cascadia Code', Menlo, Consolas, 'DejaVu Sans Mono', ui-monospace, monospace",
      tooltip: 'Monospace font used in the editor.',
    },
    {
      key: 'editorFontSize',
      label: 'Font Size (px)',
      type: 'number',
      category: 'Editor',
      defaultValue: 14,
      min: 8,
      max: 32,
      tooltip: 'Editor font size in pixels.',
    },
    {
      key: 'editorWordWrap',
      label: 'Word Wrap',
      type: 'boolean',
      category: 'Editor',
      defaultValue: true,
      tooltip: 'Wrap long lines at the viewport edge.',
    },
    {
      key: 'wrapGuideColumn',
      label: 'Wrap Column',
      type: 'number',
      category: 'Editor',
      defaultValue: 0,
      min: 0,
      max: 500,
      tooltip: 'Hard wrap + show a guide at this column (0 wraps at viewport)',
    },
    {
      key: 'showWhitespace',
      label: 'Whitespace Displayed',
      type: 'boolean',
      category: 'Editor',
      defaultValue: false,
      tooltip: 'Display whitespace characters (spaces, tabs) in the editor.',
    },
    {
      key: 'enableAutocomplete',
      label: 'Autocomplete',
      type: 'boolean',
      category: 'Editor',
      defaultValue: true,
      tooltip: 'Show autocomplete suggestions as you type.',
    },
    {
      key: 'autocompleteDelay',
      label: 'Autocomplete Delay (ms)',
      type: 'number',
      category: 'Editor',
      defaultValue: 850,
      min: 0,
      max: 2000,
      tooltip: 'Delay in milliseconds before autocomplete suggestions appear.',
    },
    {
      key: 'showMinimap',
      label: 'Minimap',
      type: 'boolean',
      category: 'Editor',
      defaultValue: false,
      tooltip: 'Replace the scrollbar with a minimap overview of the document',
    },
    {
      key: 'writerWrapLength',
      label: 'Writer Mode Wrap Length',
      type: 'number',
      category: 'Editor',
      defaultValue: 100,
      min: 40,
      max: 200,
      tooltip: 'Maximum line width in characters when Writer Mode is active.',
    },
    {
      key: 'defaultIndent',
      label: 'Indent Default (spaces)',
      type: 'number',
      category: 'Editor',
      defaultValue: 2,
      min: 2,
      max: 8,
      tooltip: 'Number of spaces used for indentation.',
    },
    {
      key: 'recentChangesCount',
      label: 'Recent Changes Count',
      type: 'number',
      category: 'Editor',
      defaultValue: 16,
      min: 0,
      max: 99,
      tooltip: 'Highlight recent changes. Maximum 99. Set to 0 to disable count-based filtering.',
    },
    {
      key: 'recentChangesTimespan',
      label: 'Recent Changes Time Span (secs)',
      type: 'number',
      category: 'Editor',
      defaultValue: 600,
      min: 0,
      max: 9999,
      groupWith: 'recentChangesCount',
      tooltip: 'Max 9999. Set to 0 for unlimited time.',
    },
    {
      key: 'autoSaveEnabled',
      label: 'Auto Save',
      type: 'boolean',
      category: 'Editor',
      defaultValue: false,
      tooltip: 'Automatically save the active file at a set interval.',
    },
    {
      key: 'autoSaveInterval',
      label: 'Auto Save Interval (secs)',
      type: 'number',
      category: 'Editor',
      defaultValue: 60,
      min: 5,
      max: 3600,
      visibleWhen: { key: 'autoSaveEnabled', value: true },
      tooltip: 'Seconds between automatic saves (min 5, max 3600).',
    },
    {
      key: 'lineEndingPreference',
      label: 'Line Ending',
      type: 'select',
      category: 'Editor',
      defaultValue: 'system',
      options: ['system', 'LF', 'CRLF'],
      optionLabels: ['System Default', 'LF (Unix)', 'CRLF (Windows)'],
      tooltip: 'Line ending style for new files.',
    },
    {
      key: 'formatOnSave',
      label: 'Format on Save',
      type: 'boolean',
      category: 'Formatter',
      defaultValue: false,
      tooltip: 'Automatically format the document when saving.',
    },
    {
      key: 'formatOnPaste',
      label: 'Format on Paste',
      type: 'boolean',
      category: 'Formatter',
      defaultValue: false,
      tooltip: 'Automatically format pasted content.',
    },
    {
      key: 'formatterBulletChar',
      label: 'Bullet Character',
      type: 'select',
      category: 'Formatter',
      defaultValue: '-',
      options: ['-', '*', '+'],
      tooltip: 'Character used for unordered list bullets.',
    },
    {
      key: 'formatterEmphasisChar',
      label: 'Emphasis Character',
      type: 'select',
      category: 'Formatter',
      defaultValue: '*',
      options: ['*', '_'],
      optionLabels: ['*', '_'],
      tooltip: 'Character used for italic/bold emphasis.',
    },
    {
      key: 'formatterCodeFence',
      label: 'Code Fence Style',
      type: 'select',
      category: 'Formatter',
      defaultValue: '```',
      options: ['```', '~~~'],
      tooltip: 'Code fence delimiter style.',
    },
    {
      key: 'tabWidthMin',
      label: 'Tab Width Minimum (px)',
      type: 'number',
      category: 'Interface',
      defaultValue: 120,
      min: 80,
      max: 300,
      tooltip: 'Minimum width of tabs in pixels.',
    },
    {
      key: 'tabWidthMax',
      label: 'Tab Width Maximum (px)',
      type: 'number',
      category: 'Interface',
      defaultValue: 180,
      min: 100,
      max: 400,
      tooltip: 'Maximum width of tabs in pixels.',
    },
    {
      key: 'collapsePinnedTabs',
      label: 'Pinned Tabs Collapse',
      type: 'boolean',
      category: 'Interface',
      defaultValue: false,
      tooltip: 'Shrink pinned tabs to icon only',
    },
    {
      key: 'tabCycling',
      label: 'Tab Cycling',
      type: 'select',
      category: 'Interface',
      defaultValue: 'mru',
      options: ['sequential', 'mru'],
      optionLabels: ['Sequential', 'MRU'],
      tooltip: 'Sequential: cycle tabs in order. MRU: cycle to most recently used tab.',
    },
    {
      key: 'tabNameFromContent',
      label: 'Tabs Named from Content',
      type: 'boolean',
      category: 'Interface',
      defaultValue: false,
      tooltip:
        'Automatically name unsaved tabs from first meaningful line of content (skips structural-only lines like brackets, strips leading #)',
    },
    {
      key: 'enableClosedTabHistory',
      label: 'Recently Closed on New Docs',
      type: 'boolean',
      category: 'Interface',
      defaultValue: true,
      tooltip: 'Show a list of recently closed files on new, empty documents for quick reopening.',
    },
    {
      key: 'recentFilesLimit',
      label: 'Recent Files Limit',
      type: 'number',
      category: 'Interface',
      defaultValue: 99,
      min: 0,
      max: 999,
      step: 1,
      tooltip: 'Maximum number of recent files to remember. Change applies after next file open.',
    },
    {
      key: 'newTabPosition',
      label: 'Tabs Created At',
      type: 'select',
      category: 'Interface',
      defaultValue: 'end',
      options: ['beginning', 'right', 'end'],
      optionLabels: ['The Beginning', 'The Right', 'The End'],
      tooltip: 'Where new tabs are inserted in the tab bar.',
    },
    {
      key: 'startupBehavior',
      label: 'Tab Startup',
      type: 'select',
      category: 'Interface',
      defaultValue: 'last-focused',
      options: ['first', 'last-focused', 'new'],
      optionLabels: ['Show First', 'Show Last Focused', 'Create New'],
      tooltip: 'What to show when the application starts.',
    },
    {
      key: 'statusBarTransparency',
      label: 'Status Bar Transparency',
      type: 'range',
      category: 'Interface',
      defaultValue: 0,
      min: 0,
      max: 100,
      step: 5,
      tooltip: 'Status bar background opacity. Lower values are more transparent.',
    },
    {
      key: 'tooltipDelay',
      label: 'Tooltip Delay (ms)',
      type: 'number',
      category: 'Interface',
      defaultValue: 1250,
      min: 0,
      max: 5000,
      tooltip: 'Delay in milliseconds before tooltips appear.',
    },
    {
      key: 'findPanelTransparent',
      label: 'Find Panel Hides',
      type: 'boolean',
      category: 'Interface',
      defaultValue: false,
      tooltip: 'The Find Panel will be almost completely transparent when not hovered.',
    },
    {
      key: 'findPanelCloseOnBlur',
      label: 'Find Panel Closes on Blur',
      type: 'boolean',
      category: 'Interface',
      defaultValue: false,
      tooltip: 'The Find Panel will close on any click outside the Find Panel.',
    },
    {
      key: 'confirmationSuppressed',
      label: 'Confirmations Suppressed',
      type: 'boolean',
      category: 'Interface',
      defaultValue: false,
      tooltip: 'Suppress confirmation dialogs (unsaved changes will be discarded immediately when closing tabs).',
    },

    {
      key: 'previewFontFamily',
      label: 'Font Family',
      type: 'text',
      category: 'Preview',
      defaultValue: 'system-ui, -apple-system, sans-serif',
      tooltip: 'Font used in the preview pane.',
    },
    {
      key: 'previewFontSize',
      label: 'Font Size (px)',
      type: 'number',
      category: 'Preview',
      defaultValue: 16,
      min: 10,
      max: 32,
      tooltip: 'Preview font size in pixels.',
    },
    {
      key: 'markdownFlavor',
      label: 'Markdown Flavor',
      type: 'select',
      category: 'Preview',
      defaultValue: 'gfm',
      options: ['gfm', 'commonmark'],
      optionLabels: ['GitHub Flavored Markdown', 'CommonMark'],
      tooltip: 'Markdown parsing flavor. GFM includes tables, strikethrough, and task lists.',
    },

    {
      key: 'languageDictionaries',
      label: 'Language Dictionaries',
      type: 'dictionary-multi-select',
      category: 'Spellcheck',
      defaultValue: ['en-US'],
      tooltip: 'Select one or more languages, duplicate words are removed by the app.',
      onChange: reloadSpellcheck,
    },
    {
      key: 'technicalDictionaries',
      label: 'Technical Dictionaries',
      type: 'boolean',
      category: 'Spellcheck',
      defaultValue: false,
      tooltip: 'Include non-language dictionaries (coding, companies, frameworks, etc.).',
      onChange: reloadSpellcheck,
    },
    {
      key: 'scienceDictionaries',
      label: 'Science+ Dictionaries',
      type: 'boolean',
      category: 'Spellcheck',
      defaultValue: false,
      tooltip: 'Includes scientific (670k+) and medical (98k+) terms. Warning: Large download and higher memory usage.',
      onChange: reloadSpellcheck,
    },

    ...(isWindows
      ? [
          {
            key: 'windowsContextMenu',
            label: 'Context Menu Enabled',
            type: 'custom-context-menu',
            category: 'System',
            defaultValue: false,
            tooltip: "Enable 'Open with MarkdownRS' in Windows Explorer context menu.",
          },
        ]
      : []),
  ];
}
