import { openFind, openReplace } from '$lib/stores/interfaceStore.svelte';
import { dispatchKeyEvent } from './helpers';
import type { Command } from './types';

export const editorCommands: Command[] = [
  {
    id: 'editor.toggleComment',
    label: 'Editor: Toggle Line Comment',
    category: 'Editor',
    defaultKey: 'ctrl+/',
    handler: () => dispatchKeyEvent('/', true),
  },
  {
    id: 'editor.find',
    label: 'Editor: Find',
    category: 'Editor',
    defaultKey: 'ctrl+f',
    global: true,
    handler: openFind,
  },
  {
    id: 'editor.replace',
    label: 'Editor: Replace',
    category: 'Editor',
    defaultKey: 'ctrl+h',
    global: true,
    handler: openReplace,
  },
  {
    id: 'editor.duplicateLine',
    label: 'Editor: Duplicate Line/Selection',
    category: 'Editor',
    defaultKey: 'ctrl+shift+d',
    handler: () => dispatchKeyEvent('d', true, true),
  },
  {
    id: 'editor.deleteLine',
    label: 'Editor: Delete Line',
    category: 'Editor',
    defaultKey: 'ctrl+shift+k',
    handler: () => dispatchKeyEvent('k', true, true),
  },
  {
    id: 'editor.moveLineUp',
    label: 'Editor: Move Line Up',
    category: 'Editor',
    defaultKey: 'alt+arrowup',
    handler: () => dispatchKeyEvent('ArrowUp', false, false, true),
  },
  {
    id: 'editor.moveLineDown',
    label: 'Editor: Move Line Down',
    category: 'Editor',
    defaultKey: 'alt+arrowdown',
    handler: () => dispatchKeyEvent('ArrowDown', false, false, true),
  },
  {
    id: 'editor.copyLineUp',
    label: 'Editor: Copy Line Up',
    category: 'Editor',
    defaultKey: 'shift+alt+arrowup',
    handler: () => dispatchKeyEvent('ArrowUp', false, true, true),
  },
  {
    id: 'editor.addCursorAbove',
    label: 'Editor: Add Cursor Above',
    category: 'Editor',
    defaultKey: 'ctrl+alt+arrowup',
    handler: () => dispatchKeyEvent('ArrowUp', true, false, true),
  },
  {
    id: 'editor.addCursorBelow',
    label: 'Editor: Add Cursor Below',
    category: 'Editor',
    defaultKey: 'ctrl+alt+arrowdown',
    handler: () => dispatchKeyEvent('ArrowDown', true, false, true),
  },
  {
    id: 'editor.selectLine',
    label: 'Editor: Select Line',
    category: 'Editor',
    defaultKey: 'ctrl+l',
    handler: () => dispatchKeyEvent('l', true),
  },
  {
    id: 'editor.gotoMatchingBracket',
    label: 'Editor: Go to Matching Bracket',
    category: 'Editor',
    defaultKey: 'ctrl+shift+\\',
    handler: () => dispatchKeyEvent('\\', true, true),
  },
  {
    id: 'editor.indent',
    label: 'Editor: Indent',
    category: 'Editor',
    defaultKey: 'ctrl+]',
    handler: () => dispatchKeyEvent(']', true),
  },
  {
    id: 'editor.outdent',
    label: 'Editor: Outdent',
    category: 'Editor',
    defaultKey: 'ctrl+[',
    handler: () => dispatchKeyEvent('[', true),
  },
];
