import {
  addCursorAbove,
  addCursorBelow,
  copyLineDown,
  copyLineUp,
  cursorMatchingBracket,
  deleteLine,
  indentLess,
  indentMore,
  moveLineDown,
  moveLineUp,
  selectLine,
} from "@codemirror/commands";
import { openFind, openReplace } from "$lib/stores/interfaceStore.svelte";
import { toggleSelectionComment } from "$lib/utils/commentToggle";
import { runEditorCommand } from "./helpers";
import type { Command } from "./types";

export const editorCommands: Command[] = [
  {
    id: "editor.toggleComment",
    label: "Toggle Line Comment",
    labelKey: "command.toggleComment",
    category: "commandCategory.editor",
    defaultKey: "ctrl+/",
    handler: () => runEditorCommand(toggleSelectionComment),
  },
  {
    id: "editor.find",
    label: "Find",
    labelKey: "command.find",
    category: "commandCategory.editor",
    defaultKey: "ctrl+f",
    global: true,
    handler: openFind,
  },
  {
    id: "editor.replace",
    label: "Replace",
    labelKey: "command.replace",
    category: "commandCategory.editor",
    defaultKey: "ctrl+h",
    global: true,
    handler: openReplace,
  },
  {
    id: "editor.duplicateLine",
    label: "Duplicate Line/Selection",
    labelKey: "command.duplicateLine",
    category: "commandCategory.editor",
    defaultKey: "ctrl+shift+d",
    handler: () => runEditorCommand(copyLineDown),
  },
  {
    id: "editor.deleteLine",
    label: "Delete Line",
    labelKey: "command.deleteLine",
    category: "commandCategory.editor",
    defaultKey: "ctrl+shift+k",
    handler: () => runEditorCommand(deleteLine),
  },
  {
    id: "editor.moveLineUp",
    label: "Move Line Up",
    labelKey: "command.moveLineUp",
    category: "commandCategory.editor",
    defaultKey: "alt+arrowup",
    handler: () => runEditorCommand(moveLineUp),
  },
  {
    id: "editor.moveLineDown",
    label: "Move Line Down",
    labelKey: "command.moveLineDown",
    category: "commandCategory.editor",
    defaultKey: "alt+arrowdown",
    handler: () => runEditorCommand(moveLineDown),
  },
  {
    id: "editor.copyLineUp",
    label: "Copy Line Up",
    labelKey: "command.copyLineUp",
    category: "commandCategory.editor",
    defaultKey: "shift+alt+arrowup",
    handler: () => runEditorCommand(copyLineUp),
  },
  {
    id: "editor.addCursorAbove",
    label: "Add Cursor Above",
    labelKey: "command.addCursorAbove",
    category: "commandCategory.editor",
    defaultKey: "ctrl+alt+arrowup",
    handler: () => runEditorCommand(addCursorAbove),
  },
  {
    id: "editor.addCursorBelow",
    label: "Add Cursor Below",
    labelKey: "command.addCursorBelow",
    category: "commandCategory.editor",
    defaultKey: "ctrl+alt+arrowdown",
    handler: () => runEditorCommand(addCursorBelow),
  },
  {
    id: "editor.selectLine",
    label: "Select Line",
    labelKey: "command.selectLine",
    category: "commandCategory.editor",
    defaultKey: "ctrl+l",
    handler: () => runEditorCommand(selectLine),
  },
  {
    id: "editor.gotoMatchingBracket",
    label: "Go to Matching Bracket",
    labelKey: "command.gotoMatchingBracket",
    category: "commandCategory.editor",
    defaultKey: "ctrl+shift+\\",
    handler: () => runEditorCommand(cursorMatchingBracket),
  },
  {
    id: "editor.indent",
    label: "Indent",
    labelKey: "command.indent",
    category: "commandCategory.editor",
    defaultKey: "ctrl+]",
    handler: () => runEditorCommand(indentMore),
  },
  {
    id: "editor.outdent",
    label: "Outdent",
    labelKey: "command.outdent",
    category: "commandCategory.editor",
    defaultKey: "ctrl+[",
    handler: () => runEditorCommand(indentLess),
  },
];
