import {
  addCursorAbove,
  addCursorBelow,
  copyLineDown,
  copyLineUp,
  cursorMatchingBracket,
  deleteLine,
  indentLess,
  indentMore,
  moveLineDown,
  moveLineUp,
  selectLine,
} from "@codemirror/commands";
import { openFind, openReplace } from "$lib/stores/interfaceStore.svelte";
import { toggleSelectionComment } from "$lib/utils/commentToggle";
import { runEditorCommand } from "./helpers";
import type { Command } from "./types";

export const editorCommands: Command[] = [
  {
    id: "editor.toggleComment",
    label: "Editor: Toggle Line Comment",
    category: "Editor",
    defaultKey: "ctrl+/",
    handler: () => runEditorCommand(toggleSelectionComment),
  },
  {
    id: "editor.find",
    label: "Editor: Find",
    category: "Editor",
    defaultKey: "ctrl+f",
    global: true,
    handler: openFind,
  },
  {
    id: "editor.replace",
    label: "Editor: Replace",
    category: "Editor",
    defaultKey: "ctrl+h",
    global: true,
    handler: openReplace,
  },
  {
    id: "editor.duplicateLine",
    label: "Editor: Duplicate Line/Selection",
    category: "Editor",
    defaultKey: "ctrl+shift+d",
    handler: () => runEditorCommand(copyLineDown),
  },
  {
    id: "editor.deleteLine",
    label: "Editor: Delete Line",
    category: "Editor",
    defaultKey: "ctrl+shift+k",
    handler: () => runEditorCommand(deleteLine),
  },
  {
    id: "editor.moveLineUp",
    label: "Editor: Move Line Up",
    category: "Editor",
    defaultKey: "alt+arrowup",
    handler: () => runEditorCommand(moveLineUp),
  },
  {
    id: "editor.moveLineDown",
    label: "Editor: Move Line Down",
    category: "Editor",
    defaultKey: "alt+arrowdown",
    handler: () => runEditorCommand(moveLineDown),
  },
  {
    id: "editor.copyLineUp",
    label: "Editor: Copy Line Up",
    category: "Editor",
    defaultKey: "shift+alt+arrowup",
    handler: () => runEditorCommand(copyLineUp),
  },
  {
    id: "editor.addCursorAbove",
    label: "Editor: Add Cursor Above",
    category: "Editor",
    defaultKey: "ctrl+alt+arrowup",
    handler: () => runEditorCommand(addCursorAbove),
  },
  {
    id: "editor.addCursorBelow",
    label: "Editor: Add Cursor Below",
    category: "Editor",
    defaultKey: "ctrl+alt+arrowdown",
    handler: () => runEditorCommand(addCursorBelow),
  },
  {
    id: "editor.selectLine",
    label: "Editor: Select Line",
    category: "Editor",
    defaultKey: "ctrl+l",
    handler: () => runEditorCommand(selectLine),
  },
  {
    id: "editor.gotoMatchingBracket",
    label: "Editor: Go to Matching Bracket",
    category: "Editor",
    defaultKey: "ctrl+shift+\\",
    handler: () => runEditorCommand(cursorMatchingBracket),
  },
  {
    id: "editor.indent",
    label: "Editor: Indent",
    category: "Editor",
    defaultKey: "ctrl+]",
    handler: () => runEditorCommand(indentMore),
  },
  {
    id: "editor.outdent",
    label: "Editor: Outdent",
    category: "Editor",
    defaultKey: "ctrl+[",
    handler: () => runEditorCommand(indentLess),
  },
];
