import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const rootDir = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const packageJsonPath = path.join(rootDir, 'package.json');
const pkgbuildPath = path.join(rootDir, 'PKGBUILD');
const tauriConfPath = path.join(rootDir, 'src-tauri', 'tauri.conf.json');
const cargoTomlPath = path.join(rootDir, 'src-tauri', 'Cargo.toml');
const cargoLockPath = path.join(rootDir, 'src-tauri', 'Cargo.lock');
const dotPkgPkgbuildPath = path.join(rootDir, '.pkg', 'PKGBUILD');

const VERSION_RE = /^\d+\.\d+\.\d+$/;
const JSON_VERSION_RE = /("version": ")\d+\.\d+\.\d+(")/;
const CARGO_TOML_VERSION_RE = /(\[package\][\s\S]*?^version = ")([^"]+)(")/m;
const CARGO_LOCK_VERSION_RE = /(^\[\[package\]\]\nname = "markdown-rs"\nversion = ")\d+\.\d+\.\d+(")/m;
const PKGBUILD_VERSION_RE = /^(pkgver=).+$/m;

function fail(message) {
  console.error(`[version] ${message}`);
  process.exit(1);
}

function readJson(filePath) {
  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf8'));
  } catch (error) {
    fail(`cannot read ${filePath}: ${error.message}`);
  }
}

function updateJsonVersion(filePath, newVersion, label) {
  try {
    const content = fs.readFileSync(filePath, 'utf8');
    JSON.parse(content);
    if (!JSON_VERSION_RE.test(content)) {
      fail(`version pattern not found in ${filePath}`);
    }
    fs.writeFileSync(filePath, content.replace(JSON_VERSION_RE, `$1${newVersion}$2`));
  } catch (error) {
    fail(`cannot update ${label} (${filePath}): ${error.message}`);
  }
}

function updateTextFile(filePath, regex, replacement, label) {
  try {
    if (!fs.existsSync(filePath)) {
      console.warn(`[version] skipping ${label}: ${filePath} not found`);
      return;
    }
    const content = fs.readFileSync(filePath, 'utf8');
    if (!regex.test(content)) {
      console.warn(`[version] skipping ${label}: version pattern not found in ${filePath}`);
      return;
    }
    fs.writeFileSync(filePath, content.replace(regex, replacement));
  } catch (error) {
    fail(`cannot update ${label} (${filePath}): ${error.message}`);
  }
}

function runGit(args) {
  try {
    execFileSync('git', args, { stdio: 'inherit' });
  } catch (error) {
    fail(`git ${args[0]} failed: ${error.stderr?.toString().trim() ?? error.message}`);
  }
}

const args = process.argv.slice(2);
const shouldGit = args.includes('--git');
const versionArg = args.find((arg) => !arg.startsWith('--')) ?? '';

// 1. Determine new version
const packageJson = readJson(packageJsonPath);
const currentVersion = packageJson.version;

let newVersion = versionArg;
if (!newVersion) {
  const parts = currentVersion.split('.').map((n) => parseInt(n, 10));
  if (parts.length !== 3 || parts.some(Number.isNaN)) {
    fail(`cannot parse current version "${currentVersion}" from package.json`);
  }
  parts[2] += 1;
  newVersion = parts.join('.');
}

if (!VERSION_RE.test(newVersion)) {
  fail(`invalid version "${newVersion}" (expected x.y.z)`);
}

// 2. package.json
updateJsonVersion(packageJsonPath, newVersion, 'package.json');

// 3. tauri.conf.json
updateJsonVersion(tauriConfPath, newVersion, 'tauri.conf.json');

// 4. Cargo.toml
updateTextFile(cargoTomlPath, CARGO_TOML_VERSION_RE, `$1${newVersion}$3`, 'Cargo.toml');

// 5. Cargo.lock (best effort; regenerated by cargo after `bun run clean`)
updateTextFile(cargoLockPath, CARGO_LOCK_VERSION_RE, `$1${newVersion}$2`, 'Cargo.lock');

// 6. PKGBUILD
updateTextFile(pkgbuildPath, PKGBUILD_VERSION_RE, `$1${newVersion}`, 'PKGBUILD');

// 7. .pkg/PKGBUILD (best effort; recreated by `bun run package`)
updateTextFile(dotPkgPkgbuildPath, PKGBUILD_VERSION_RE, `$1${newVersion}`, '.pkg/PKGBUILD');

// 8. Git integration
if (shouldGit) {
  const files = [packageJsonPath, pkgbuildPath, tauriConfPath, cargoTomlPath, cargoLockPath];
  if (fs.existsSync(dotPkgPkgbuildPath)) {
    files.push(dotPkgPkgbuildPath);
  }
  const tagName = `v${newVersion}`;

  runGit(['add', ...files]);
  runGit(['commit', '-m', `chore: release v${newVersion}`]);
  runGit(['tag', '-a', tagName, '-m', tagName]);
  runGit(['push', '--follow-tags']);
}

console.log(`[version] bumped ${currentVersion} -> ${newVersion}`);
